name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - uses: actions/checkout@v2
    - name: Install Deps
      run: sudo apt update && sudo apt install -y ccache
    - name: Setup Toolchain
      run: mkdir -p ~/android/toolchain/gcc-arm-x86_64-aarch64-none-linux-gnu && wget "https://developer.arm.com/-/media/Files/downloads/gnu-a/9.2-2019.12/binrel/gcc-arm-9.2-2019.12-x86_64-aarch64-none-linux-gnu.tar.xz" -O ~/android/toolchain/gcc-arm-x86_64-aarch64-none-linux-gnu.tar.xz && tar -xvf ~/android/toolchain/gcc-arm-x86_64-aarch64-none-linux-gnu.tar.xz -C ~/android/toolchain/gcc-arm-x86_64-aarch64-none-linux-gnu
    - name: build
      run: ./build.sh 965
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: Auto generated release
        draft: true
        prerelease: false
    - name: Upload Assets to Release with a wildcard
      uses: csexton/release-asset-action@v2
      with:
        pattern: "build/*"
        github-token: ${{ secrets.GITHUB_TOKEN }}
        release-url: ${{ steps.create_release.outputs.upload_url }}
