name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: set permissions
      run: chmod 777 -Rf .
    - uses: actions/cache@v1
      id: cache-toolchain
      with:
        path: ~/android/toolchain/gcc-arm-x86_64-aarch64-none-linux-gnu
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Setup Toolchain
      if: steps.cache-toolchain.outputs.cache-hit != 'true'
      run: mkdir -p ~/android/toolchain/gcc-arm-x86_64-aarch64-none-linux-gnu && wget "https://developer.arm.com/-/media/Files/downloads/gnu-a/9.2-2019.12/binrel/gcc-arm-9.2-2019.12-x86_64-aarch64-none-linux-gnu.tar.xz" -O ~/android/toolchain/gcc-arm-x86_64-aarch64-none-linux-gnu.tar.xz && tar -xvf ~/android/toolchain/gcc-arm-x86_64-aarch64-none-linux-gnu.tar.xz -C ~/android/toolchain/gcc-arm-x86_64-aarch64-none-linux-gnu
    - name: build
      run: ./build.sh 965
