name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: setup toolchain
      run: mkdir -p ~/android/toolchain/gcc-arm-x86_64-aarch64-none-linux-gnu && wget "https://developer.arm.com/-/media/Files/downloads/gnu-a/9.2-2019.12/binrel/gcc-arm-9.2-2019.12-x86_64-aarch64-none-linux-gnu.tar.xz?revision=61c3be5d-5175-4db6-9030-b565aae9f766&la=en&hash=0A37024B42028A9616F56A51C2D20755C5EBBCD7" -o ~/android/toolchain/gcc-arm-x86_64-aarch64-none-linux-gnu.tar.xz && tar -xvf ~/android/toolchain/gcc-arm-x86_64-aarch64-none-linux-gnu.tar.xz -C ~/android/toolchain/gcc-arm-x86_64-aarch64-none-linux-gnu
    - name: build
      run: ./build.sh 965
